name: smartwebscraper_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - beautifulsoup4
  - requests
  - selenium
  - pandas
  - numpy
  - pip:
      - undetected-chromedriver
